#Release v0.0.10

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -132,14 +132,14 @@ jobs:
           git config user.email "github-actions@github.com"
           git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-scaffold.git
           git fetch origin main
+          git pull --rebase origin main
 
           if [[ $(git status --porcelain) ]]; then
             git add .
             git commit -m "Version Update"
-            git pull --rebase origin main
-            git push origin main
+            git push origin main || { echo 'Failed to push scaffold submodule'; exit 1; }
           else
-            echo "Repository is already up-to-date."
+            echo "Scaffold submodule repository is already up-to-date."
           fi
 
           cd ..
@@ -147,14 +147,14 @@ jobs:
           git config user.email "github-actions@github.com"
           git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-package.git
           git fetch origin main
-          
+          git pull --rebase origin main
+
           if [[ $(git status --porcelain) ]]; then
             git add .
             git commit -m "Version Update"
-            git pull --rebase origin main
-            git push origin main
+            git push origin main || { echo 'Failed to push root repository'; exit 1; }
           else
-            echo "Repository is already up-to-date."
+            echo "Root repository is already up-to-date."
           fi
 
       - name: Trigger publish workflow on Parent Repo
