QC

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -109,7 +109,7 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.XCSS_REPO_CROSS }}
 
-  publish-package:
+  version-sync:
     name: Trigger Package Release
     runs-on: ubuntu-latest
     needs: bin-release
@@ -125,14 +125,29 @@ jobs:
       - name: Sync and push submodule updates for scaffold
         run: |
           git submodule update --init ./scaffold
-          node execute
           
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+          git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-package.git
+          git fetch origin main
+          git pull --rebase origin main
+
           cd scaffold
           git config user.name "github-actions"
           git config user.email "github-actions@github.com"
           git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-scaffold.git
           git fetch origin main
           git pull --rebase origin main
+          
+          node ../execute
+          if [[ $(git status --porcelain) ]]; then
+            git add .
+            git commit -m "Version Update"
+            git push origin main || { echo 'Failed to push root repository'; exit 1; }
+          else
+            echo "Root repository is already up-to-date."
+          fi
+          cd ..
 
           if [[ $(git status --porcelain) ]]; then
             git add .
@@ -142,21 +157,18 @@ jobs:
             echo "Scaffold submodule repository is already up-to-date."
           fi
 
-          cd ..
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
-          git remote set-url origin https://x-access-token:${{ secrets.XCSS_REPO_CROSS }}@github.com/yshelldev/xcss-package.git
-          git fetch origin main
-          git pull --rebase origin main
+  publish-package:
+    name: Trigger Package Release
+    runs-on: ubuntu-latest
+    needs: version-sync
 
-          if [[ $(git status --porcelain) ]]; then
-            git add .
-            git commit -m "Version Update"
-            git push origin main || { echo 'Failed to push root repository'; exit 1; }
-          else
-            echo "Root repository is already up-to-date."
-          fi
-
+    steps:
+      - name: Checkout ${{ env.PACKAGE_REPO }} (read-only)
+        uses: actions/checkout@v4
+        with:
+          repository: ${{ env.PACKAGE_REPO }}
+          token: ${{ secrets.XCSS_REPO_CROSS }}
+          
       - name: Trigger publish workflow on Parent Repo
         uses: peter-evans/repository-dispatch@v2
         with:
@@ -167,7 +179,7 @@ jobs:
   publish-scaffold:
     name: Trigger Scaffold Release
     runs-on: ubuntu-latest
-    needs: publish-package
+    needs: version-sync
 
     steps:
       - name: Checkout ${{ env.SCAFFOLD_REPO }} (read-only)
